name: 'Build and Deploy'
on:
  push:
    branches:
    - 'main'
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  buildAndroid:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      - name: Build app
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: good-burger
          path: ./build/app/outputs/apk/release/app-release.apk

  PublishAndroid:
    runs-on: ubuntu-latest
    name: Publish to Firebase
    needs: [buildAndroid]

    steps:
      - name: Install node
        uses: actions/setup-node@v4

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Download artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: good-burger
          path: ./android-app

      - name: Publish app
        run: firebase appdistribution:distribute ./android-app/app-release.apk --app ${{ secrets.APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --groups st-stakeholders
